### ISSUE TITLE
FR: Can set the expected number of cycles and automatically perform looping. / 可设置预期的循环次数，自动进行循环

### ISSUE THREAD

**Issue by byheaven** [sethyuan/logseq-plugin-task-reminder#3]
Scenario: For example, for a certain task, this work hopes to invest 2 hours, corresponding to 4 work cycles. After setting this parameter, it can automatically complete 4 cycles and remind. It will not continue after the completion of the 4 cycles.
场景：例如对于某任务，本次工作希望投入2小时，对应4个工作循环。设定该参数后，就可以自动完成4个循环和提醒。在4个循环结束之后不再继续。

**Comment by sethyuan** [comment]
这个应该已实现了。
